global:
  smtp_smarthost: 'smtp.example.com:587'
  smtp_from: 'alertmanager@example.com'
  smtp_auth_username: 'username'
  smtp_auth_password: 'password'
  slack_api_url: 'https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX'

route:
  receiver: 'default-receiver'
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  routes:
	- match:
    	severity: 'critical'
  	receiver: 'oncall-team'
  	group_by: ['alertname', 'instance']
  	group_wait: 10s
  	group_interval: 2m
  	repeat_interval: 30m
	- match_re:
    	alertname: 'Node.*'
  	receiver: 'ops-team'

receivers:
  - name: 'default-receiver'
	email_configs:
  	- to: 'default@example.com'
  - name: 'oncall-team'
	email_configs:
  	- to: 'oncall@example.com'
  - name: 'ops-team'
	slack_configs:
  	- channel: '#ops-alerts'
    	send_resolved: true

inhibit_rules:
  - source_match:
  	severity: 'critical'
	target_match:
  	severity: 'warning'
	equal: ['alertname', 'instance']
